# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0e017a857f7f82cb469d0d4678119e1801e20261090c55d016ea5ca139f3556ee2ba62b2defc4391a95d50f30cf25f0dbfea1030d6382607d86f36b44e3afc6

test:
  secret_key_base: 8c9c3cfc5ca1a6f4becdc58f69c55597b6b460c64c6b858d5bc51f7f79a1507bd20980c13cc81b29825150ff2b4bfdd1d5feaf1d8d537b75e499246e341ff800

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
